services:
  db:
    image: postgres:16-alpine
    container_name: postgres-crypto-aggregator
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "crypto-aggregator"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crypto-aggregator"]
      interval: 5s
      timeout: 5s
      retries: 5